# Generated by Django 3.1.4 on 2021-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20210613_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_news',
        ),
        migrations.AddField(
            model_name='company',
            name='company_news',
            field=models.ManyToManyField(blank=True, null=True, to='companys.News', verbose_name='Новости компании'),
        ),
    ]
