# Generated by Django 3.1.4 on 2021-06-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_auto_20210613_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_news',
            field=models.ManyToManyField(to='companys.News', verbose_name='Новости компании'),
        ),
    ]
